#pragma once

enum class CBUFFER_LOCATION
{
	VERTEX_SHADER_CBUFFER,
	HULL_SHADER_CBUFFER,
	DOMAIN_SHADER_CBUFFER,
	GEOMETRY_SHADER_CBUFFER,
	PIXEL_SHADER_CBUFFER,
	COMPUTE_SHADER_CBUFFER
};

enum class TEXTURE_LOCATION
{
	VERTEX_SHADER_TEXTURE,
	HULL_SHADER_TEXTURE,
	DOMAIN_SHADER_TEXTURE,
	GEOMETRY_SHADER_TEXTURE,
	PIXEL_SHADER_TEXTURE,
	COMPUTE_SHADER_TEXTURE
};

enum class SAMPLER_LOCATION
{
	VERTEX_SHADER_SAMPLER,
	HULL_SHADER_SAMPLER,
	DOMAIN_SHADER_SAMPLER,
	GEOMETRY_SHADER_SAMPLER,
	PIXEL_SHADER_SAMPLER,
	COMPUTE_SHADER_SAMPLER
};

enum class FILTERING
{
	NEAREST,
	BILINEAR,
	TRILINEAR,
	ANISOTROPIC_X4,
	ANISOTROPIC_X16
};